# Generated by Django 5.0.7 on 2025-11-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_transaccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='detalle_pedido',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
