# Generated by Django 5.0.7 on 2025-12-02 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('problema', 'Problema/Incidencia'), ('analisis', 'Análisis de Datos'), ('auditoria', 'Auditoría'), ('ventas', 'Reporte de Ventas'), ('inventario', 'Inventario'), ('financiero', 'Financiero')], default='analisis', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('revisando', 'En Revisión'), ('completado', 'Completado'), ('archivado', 'Archivado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('datos_json', models.JSONField(blank=True, null=True, verbose_name='Datos del análisis')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('stock', 'Falta de Stock'), ('calidad', 'Problema de Calidad'), ('logistica', 'Problema Logístico'), ('sistema', 'Error del Sistema'), ('cliente', 'Queja de Cliente'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Severidad')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('producto_afectado', models.CharField(blank=True, max_length=200, verbose_name='Producto afectado')),
                ('cantidad_afectada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad afectada')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='core.reporte', verbose_name='Reporte relacionado')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción realizada')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, verbose_name='Estado nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.reporte', verbose_name='Reporte')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de Reporte',
                'verbose_name_plural': 'Seguimientos de Reportes',
                'ordering': ['-fecha'],
            },
        ),
    ]
