# Generated by Django 5.0.7 on 2025-12-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario_registrado', 'Nuevo usuario registrado'), ('usuario_actualizado', 'Usuario actualizado'), ('pedido_creado', 'Pedido creado'), ('pedido_actualizado', 'Pedido actualizado'), ('pedido_completado', 'Pedido completado'), ('producto_creado', 'Producto creado'), ('producto_actualizado', 'Producto actualizado'), ('producto_eliminado', 'Producto eliminado'), ('reporte_creado', 'Reporte creado'), ('incidencia_creada', 'Incidencia creada')], max_length=50, verbose_name='Tipo de actividad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('objeto_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de objeto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad Reciente',
                'verbose_name_plural': 'Actividades Recientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
