# Generated by Django 5.2.7 on 2025-12-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_itemcarrito_color'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenColorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=7, verbose_name='Color Hex')),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL Imagen Generada')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_cache', to='carrito.productovariante')),
            ],
            options={
                'verbose_name': 'Imagen Color Cache',
                'verbose_name_plural': 'Imágenes Color Cache',
                'ordering': ['-fecha_generacion'],
                'unique_together': {('variante', 'color_hex')},
            },
        ),
    ]
