# Generated by Django 5.0.7 on 2025-12-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_pedido_options_pedido_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
