# Generated by Django 5.2 on 2025-10-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_producto_categoria_producto_stock_alter_carrito_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='UsuarioPersonalizado',
            new_name='usuario',
        ),
    ]
