# Generated by Django 5.0.7 on 2025-12-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_producto_en_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
