# Generated by Django 5.0.7 on 2025-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_itemcarrito_color'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['en_oferta'], name='carrito_pro_en_ofer_3aa172_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='carrito_pro_nombre_c8118f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'en_oferta'], name='carrito_pro_categor_4e71c1_idx'),
        ),
    ]
