# Generated by Django 5.0.7 on 2025-11-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_producto_imagen_url_alter_producto_descripcion_and_more'),
        ('carrito', '0004_rename_usuariopersonalizado_pedido_usuario'),
    ]

    operations = [
    ]
