# Generated by Django 5.2.7 on 2025-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_merge_20251107_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
