# Generated by Django 5.0.7 on 2025-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_merge_20251114_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
