# Generated by Django 5.0.7 on 2025-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Activado'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Clave secreta 2FA'),
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
    ]
