# Generated by Django 5.0.7 on 2025-11-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_producto_en_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='en_oferta',
        ),
    ]
