# Generated by Django 5.2.7 on 2025-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_itemcarrito_talla_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='carrito.producto'),
        ),
    ]
