# Generated by Django 5.0.7 on 2025-12-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_usuariopersonalizado_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
    ]
