# Generated by Django 5.0.7 on 2025-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_producto_talla_usuariopersonalizado_favoritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id']},
        ),
        # Campo talla ya existe, se removió AddField
        # Los índices se agregan manualmente al final con SQL directo
        # No modificamos los campos existentes para evitar conflictos con ENUMs
        migrations.AddIndex(
            model_name='itemcarrito',
            index=models.Index(fields=['carrito', 'producto'], name='carrito_ite_carrito_f6f7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-fecha'], name='carrito_ped_usuario_0a93c7_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'destacado'], name='carrito_pro_categor_fe82a8_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-precio'], name='carrito_pro_precio_aabbe6_idx'),
        ),
    ]
