# Generated by Django 5.0.7 on 2025-12-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_usuariopersonalizado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
