# Generated by Django 5.0.7 on 2025-11-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_remove_producto_en_oferta'),
        ('carrito', '0009_add_manual_indexes'),
    ]

    operations = [
    ]
