# Generated by Django 5.2.7 on 2025-11-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_remove_producto_en_oferta'),
        ('carrito', '0010_add_colores'),
    ]

    operations = [
    ]
