# Generated by Django 5.0.7 on 2025-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_merge_20251113_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
