# Generated by Django 5.2.7 on 2025-11-14 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0011_merge_0007_remove_producto_en_oferta_0010_add_colores'),
    ]

    operations = [
        # Removemos AddField de talla porque ya existe
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('ropa', 'Ropa (camisetas, buzos, camisas)'), ('pantalones', 'Pantalones'), ('zapatos', 'Zapatos')], default='ropa', max_length=20)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='variantes/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('imagen_generada_ia', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='carrito.producto')),
            ],
            options={
                'ordering': ['talla', 'color'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='carrito.productovariante')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['producto', 'talla', 'color'], name='carrito_pro_product_52181e_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['stock'], name='carrito_pro_stock_a618e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'talla', 'color')},
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['variante', '-fecha'], name='carrito_inv_variant_496353_idx'),
        ),
    ]
