# Generated by Django 5.0.7 on 2025-11-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0011_producto_talla'),
        ('carrito', '0012_producto_talla_productovariante_inventario_and_more'),
    ]

    operations = [
    ]
