# Generated by Django 5.0.7 on 2025-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_asignar_numeros_unicos_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
