"""
Django settings for glamoure project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
SECRET_KEY = 'django-insecure-lker6vpv(__$b!l)aw_0=o_6*!lu3#v$4cocc7t+_!3dy696!='

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# CSRF Settings for development
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'carrito',
    'dashboard.apps.DashboardConfig',
    'tailwind',
    'frontend',
    'django_browser_reload',
    'pagos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glamoure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates', 'core')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glamoure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.hepzhkhrjvferjebazeg',
        'PASSWORD': 'Glamoure123*',
        'HOST': 'aws-1-us-east-2.pooler.supabase.com',
        'PORT': 6543,
        'OPTIONS': {
            'sslmode': 'require',
        },
        'CONN_MAX_AGE': 600,  # Reutilizar conexiones por 10 minutos
    }
}
# AUTH_USER_MODEL = 'core.UsuarioPersonalizado'

AUTH_USER_MODEL = 'carrito.UsuarioPersonalizado'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'static'), 
]
MEDIA_URL='media/'
MEDIA_ROOT= os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/index/'
LOGOUT_REDIRECT_URL = '/index/'

TAILWIND_APP_NAME = 'frontend'

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET", "media")

# Configuración de caché (mejora rendimiento significativamente)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Configuración de sesiones (usa caché en lugar de DB)
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Configuración de templates para producción
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]



ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1', 
    'app.glamoure.tech',
    '*.trycloudflare.com',
]

WOMPI_PUBLIC_KEY_TEST = 'pub_test_lAKUj3fWSMRl1jGXcT4pgdhhkBfr8ftP'
WOMPI_PRIVATE_KEY_TEST = 'prv_test_XefgTCdlErJRoEZfnVGtq6UhonaNlTk2'
WOMPI_EVENTS_SECRET_TEST = 'test_events_y0W4ySwZjHC1Wv0jheDOC7MIaIGkqqbC'
WOMPI_INTEGRITY_SECRET_TEST = 'test_integrity_nslqVWZD7wlccQ8AjxLYITkIgpqgFmjv'

# Claves de producción (cuando las tengas)
WOMPI_PUBLIC_KEY_PROD = ''
WOMPI_PRIVATE_KEY_PROD = ''
WOMPI_EVENTS_SECRET_PROD = ''
WOMPI_INTEGRITY_SECRET_PROD = ''

# Ambiente actual
WOMPI_ENV = 'TEST'  # Cambiar a 'PROD' en producción

# Claves activas
WOMPI_PUBLIC_KEY = WOMPI_PUBLIC_KEY_TEST if WOMPI_ENV == 'TEST' else WOMPI_PUBLIC_KEY_PROD
WOMPI_PRIVATE_KEY = WOMPI_PRIVATE_KEY_TEST if WOMPI_ENV == 'TEST' else WOMPI_PRIVATE_KEY_PROD
WOMPI_EVENTS_SECRET = WOMPI_EVENTS_SECRET_TEST if WOMPI_ENV == 'TEST' else WOMPI_EVENTS_SECRET_PROD
WOMPI_INTEGRITY_SECRET = WOMPI_INTEGRITY_SECRET_TEST if WOMPI_ENV == 'TEST' else WOMPI_INTEGRITY_SECRET_PROD

# Para webhooks
cloudflare_domains = [
    'https://app.glamoure.tech',
    'https://*.trycloudflare.com',
]

CSRF_TRUSTED_ORIGINS = ['https://checkout.wompi.co'] + cloudflare_domains + [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'


#recuperar contraseña
# Configuración para emails REALES
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juanchogamer123@gmail.com'  # Cambia por tu email real
EMAIL_HOST_PASSWORD = 'oviq ocqq edur jieg'  # La que copiaste en el paso anterior

# Configuración adicional importante
DEFAULT_FROM_EMAIL = 'juachogamer123@gmail.com'  # Mismo email de arriba
SERVER_EMAIL = 'tu_email@gmail.com'  # Para errores

# Configuración para recuperación de contraseña
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/index/'
LOGOUT_REDIRECT_URL = '/index/'

# Configuración para emails y dominio correcto
if DEBUG:
    # En desarrollo
    SITE_DOMAIN = 'http://localhost:8000'
else:
    # En producción con Cloudflare
    SITE_DOMAIN = 'https://app.glamoure.tech'

# Configuración SSL/HTTPS (al final del settings.py)
if DEBUG:
    # En desarrollo: HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    # En producción: HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True